#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'emotions-recognition','console_scripts','emt_rec_node'
__requires__ = 'emotions-recognition'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('emotions-recognition', 'console_scripts', 'emt_rec_node')()
    )
